//>>built
define("edu/wohaoo/mobile/CurriculumsView","dojo/dom-class dojo/keys dojo/query!css3 dojo/_base/connect dojo/_base/declare dijit/_WidgetBase dojo/dom-construct edu/wohaoo/mobile/AppListView dijit/registry dojox/mobile/IconItem dojo/domReady!".split(" "),function(c,g,d,f,h,m,n,k,e,l){return h([k],{loggedin:!1,searchButtonNode:null,searchInputNode:null,showFavoritesButtonNode:null,showHomeMenuButtonNode:null,homeMenuNode:null,userMenuNode:null,postCreate:function(){this.itemTemplateString='\x3cdiv class\x3d"box"\x3e\x3c/div\x3e';
this.itemClass="curriculum";this.itemMoveTo="curriculumPage";this.itemTransition="slide";this.inherited(arguments)},startup:function(){var a=this;d('button[type\x3d"submit"].icon',this.domNode).forEach(function(b){a.searchButtonNode=b});d("input#search-query",this.domNode).forEach(function(b){a.searchInputNode=b});d("span.showFavoritesButton",this.domNode).forEach(function(b){b=e.byNode(b);a.showFavoritesButtonNode=b.domNode});d("span.showHomeMenuButton",this.domNode).forEach(function(b){b=e.byNode(b);
a.showHomeMenuButtonNode=b.domNode});d(".homeMenu",this.domNode).forEach(function(b){b=e.byNode(b);a.homeMenuNode=b.domNode});d(".userMenu",this.domNode).forEach(function(b){b=e.byNode(b);a.userMenuNode=b.domNode});this._attachEvents();this.inherited(arguments)},createListItem:function(a,b,c,d,e){return new l({"class":a,dataId:b,moveTo:d,rightText:"",transition:e,label:c})},updateItemContent:function(a,b,c){},refresh:function(){c.add(this.homeMenuNode,"mblHidden");c.add(this.userMenuNode,"mblHidden");
this.searchInputNode&&(this.q=this.searchInputNode.value);this.inherited(arguments)},_attachEvents:function(){var a=this;a.searchInputNode._keyupEvent&&(a.searchInputNode._keyupEvent.remove(),a.searchInputNode._keyupEvent=null);a.searchInputNode._keyupEvent=f.connect(a.searchInputNode,"keyup",function(b){b.keyCode===g.ENTER&&(a.q=a.searchInputNode.value,""!==a.q?(c.add(a.searchButtonNode,"nav-search-active"),c.remove(a.searchButtonNode,"nav-search")):(c.remove(a.searchButtonNode,"nav-search-active"),
c.add(a.searchButtonNode,"nav-search")),a.refresh())});a.searchButtonNode._clickEvent&&(a.searchButtonNode._clickEvent.remove(),a.searchButtonNode._clickEvent=null);a.searchButtonNode._clickEvent=f.connect(a.searchButtonNode,"click",function(b){c.contains(a.searchButtonNode,"nav-search-active")?(a.q="",a.l="",a.searchInputNode.value="",a.refresh(),c.remove(a.searchButtonNode,"nav-search-active"),c.add(a.searchButtonNode,"nav-search")):(a.q=a.searchInputNode.value,a.l="",""!==a.q&&(a.refresh(),c.add(a.searchButtonNode,
"nav-search-active"),c.remove(a.searchButtonNode,"nav-search")))});a.showFavoritesButtonNode._clickEvent&&(a.showFavoritesButtonNode._clickEvent.remove(),a.showFavoritesButtonNode._clickEvent=null);a.showFavoritesButtonNode._clickEvent=f.connect(a.showFavoritesButtonNode,"click",function(b){0>a.searchInputNode.value.indexOf(":favorites")&&(a.searchInputNode.value+=":favorites");(b=Sys.getCurriculumFavorites())||(b="0");a.l=b;c.contains(a.searchButtonNode,"nav-search-active")||(c.add(a.searchButtonNode,
"nav-search-active"),c.remove(a.searchButtonNode,"nav-search"));a.refresh()});a.showHomeMenuButtonNode._clickEvent&&(a.showHomeMenuButtonNode._clickEvent.remove(),a.showHomeMenuButtonNode._clickEvent=null);a.showHomeMenuButtonNode._clickEvent=f.connect(a.showHomeMenuButtonNode,"click",function(b){Sys.getUser()?c.contains(a.userMenuNode,"mblHidden")?c.remove(a.userMenuNode,"mblHidden"):c.add(a.userMenuNode,"mblHidden"):c.contains(a.homeMenuNode,"mblHidden")?c.remove(a.homeMenuNode,"mblHidden"):c.add(a.homeMenuNode,
"mblHidden")});d(".tabBarButton",this.domNode).forEach(function(b){e.byNode(b).set("onClick",function(b){var c=e.byId(this.moveTo);c.refresh();c.animate();a.moveTo(a.id,this.moveTo,this.transition);b.stopPropagation();b.preventDefault()})})}})});
//@ sourceMappingURL=CurriculumsView.js.map