//>>built
define("edu/wohaoo/mobile/ExamView","dojo/dom-class dojo/_base/array dojo/query!css3 dojo/_base/connect dojo/_base/declare dijit/_WidgetBase dojo/dom-construct edu/wohaoo/mobile/ItemPageView dojox/mobile/ListItem dijit/registry dojo/i18n!./nls/Messages dojo/domReady!".split(" "),function(c,f,e,g,k,p,q,l,m,h,n){return k([l],{listNode:null,sessionId:0,questionId:0,optionId:0,forceNew:0,completed:!1,messages:n,questionNode:null,examDetailsNode:null,examScoreNode:null,examCommentNode:null,examNextButtonNode:null,
examRetakeButtonNode:null,postCreate:function(){this.itemTemplateString="";this.itemClass="question";var a=this;e(".questionCategory",this.domNode).forEach(function(b){a.questionNode=b});e(".examNextButton",this.domNode).forEach(function(b){a.examNextButtonNode=b});e(".examRetakeButton",this.domNode).forEach(function(b){a.examRetakeButtonNode=b});e(".examDetails",this.domNode).forEach(function(b){a.examDetailsNode=b});e("span.examScore",a.examDetailsNode).forEach(function(b){a.examScoreNode=b});e("span.examComment",
a.examDetailsNode).forEach(function(b){a.examCommentNode=b});this.inherited(arguments)},refresh:function(){this.inherited(arguments);if(this._store&&null!==this._store){var a=this;e(".itemList",this.domNode).forEach(function(b){a.listNode=b});a.completed=!1;a.forceNew=0;a.sessionid=0;a.questionId=0;a.optionId=0;this.query={id:"*",model:"exam"};this._store.fetch({query:this.query,queryOptions:{deep:!0},onBegin:function(){a.hideItems()},onComplete:function(b){f.forEach(b,function(b,e){a.sessionId=a._store.getValue(b,
"uniqueid");a._store.getValue(b,"text");a.completed=a._store.getValue(b,"completed");c.remove(a.questionNode,"mblHidden");c.remove(a.examNextButtonNode,"mblHidden");debugger;if(a.completed){if(c.add(a.questionNode,"mblHidden"),c.add(a.examNextButtonNode,"mblHidden"),c.contains(a.examDetailsNode,"mblHidden")){var d=a._store.getValue(b,"score");a.examScoreNode.innerText=d.toString();a._store.getValue(b,"passed")?a.examCommentNode.innerText="Passed":a.examCommentNode.innerText="Failed";c.remove(a.examDetailsNode,
"mblHidden")}}else c.contains(a.examDetailsNode,"mblHidden")||c.add(a.examDetailsNode,"mblHidden")})},onError:function(b){a.alert(a.errors.err102)}});this.query={id:"*",model:"question"};this._store.fetch({query:this.query,queryOptions:{deep:!0},onBegin:function(){a.hideItems()},onComplete:function(b){f.forEach(b,function(b,c){a.questionId=a._store.getValue(b,"uniqueid");var d=a._store.getValue(b,"text");a.questionNode.innerHTML=d})},onError:function(b){a.alert(a.errors.err102)}});this.query={id:"*",
model:"option"};this._store.fetch({query:this.query,queryOptions:{deep:!0},onBegin:function(){a.hideItems()},onComplete:function(b){f.forEach(b,function(b,c){var d=new m({"class":a.itemClass,dataId:a._store.getValue(b,"uniqueid"),variableHeight:!0});d.placeAt(a.listNode,"first");var e=a._store.getValue(b,"text");d.labelNode.innerHTML=e;d._checkEvent&&(d._checkEvent.remove(),d._checkEvent=null);d._checkEvent=g.connect(d.domNode,"click",function(b){b=h.byNode(this);a.optionId=b.dataId})})},onError:function(b){a.alert(a.errors.err102)}});
a.examNextButtonNode._clickEvent&&(a.examNextButtonNode._clickEvent.remove(),a.examNextButtonNode._clickEvent=null);a.examNextButtonNode._clickEvent=g.connect(a.examNextButtonNode,"click",function(b){a.completed?h.byId("dlg_message").show(a.messages.EXAM_IS_COMPLETED):(c.remove(a.questionNode,"mblHidden"),c.remove(a.examNextButtonNode,"mblHidden"),a.optionId&&(a.examNextButtonNode._clickEvent.remove(),a.examNextButtonNode._clickEvent=null,a.refresh()))});a.examRetakeButtonNode._clickEvent&&(a.examRetakeButtonNode._clickEvent.remove(),
a.examRetakeButtonNode._clickEvent=null);a.examRetakeButtonNode._clickEvent=g.connect(a.examRetakeButtonNode,"click",function(b){h.byId("dlg_confirm").show(a.messages.CONFIRM_EXAM_RETAKE,function(){c.remove(a.questionNode,"mblHidden");c.remove(a.examNextButtonNode,"mblHidden");a.forceNew=1;a.examRetakeButtonNode._clickEvent.remove();a.examRetakeButtonNode._clickEvent=null;a.refresh()})})}}})});
//@ sourceMappingURL=ExamView.js.map