//>>built
require({cache:{"url:edu/wohaoo/mobile/templates/SettingsView.html":'\x3cdiv id\x3d"settingsViewContainer"\x3e\n\t\x3ch2 class\x3d"settingsGeneralHeader" data-dojo-type\x3d"dojox.mobile.EdgeToEdgeCategory" data-dojo-props\x3d\'label:"General"\'\x3e\x3c/h2\x3e\n\t\x3cul data-dojo-type\x3d"dojox.mobile.EdgeToEdgeList"\x3e\n\t\t\x3cli class\x3d"settingsPersonalDataItem propertyListItem" data-dojo-type\x3d"dojox.mobile.ListItem" \n\t\t\t\tdata-dojo-props\x3d\'label:"Personal Details", variableHeight:true\'\n\t\t\t\tdata-dojo-attach-point\x3d"personalDataItem"\x3e\n\t\t\t\t\x3cdiv class\x3d"personalDetailsData" data-dojo-attach-point\x3d"personalDetailsData"\x3e\x3c/div\x3e\n\t\t\x3c/li\x3e\n\t\t\x3cli class\x3d"settingsLanguageItem propertyListItem"  data-dojo-type\x3d"dojox.mobile.ListItem" \n\t\t\t\tdata-dojo-props\x3d\'label:"Language", variableHeight:true\'\n\t\t\t\tdata-dojo-attach-point\x3d"languageItem"\x3e\n\t\t\t\t\x3cdiv class\x3d"languageData" data-dojo-attach-point\x3d"languageData"\x3e\x3c/div\x3e\n\t\t\x3c/li\x3e\n\t\x3c/ul\x3e\n\x3c/div\x3e'}});
define("edu/wohaoo/mobile/SettingsView","dojo/request dojo/dom-class dojo/_base/array dojo/query!css3 dojo/_base/connect dojo/_base/declare dijit/_WidgetBase dojo/dom-construct edu/wohaoo/mobile/_AppViewMixin dojox/mobile/ScrollableView dijit/registry dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/i18n!./nls/Messages dojo/text!./templates/SettingsView.html dojo/data/ItemFileReadStore dojo/domReady!".split(" "),function(g,s,t,h,c,k,u,v,l,m,e,n,p,f,q,r){return k([m,n,p,l],{templateString:q,
messages:f,personalDataItem:null,languageItem:null,messages:f,FirstName:"",LastName:"",BirthDate:"",LanguageCode:"",_setFirstNameAttr:function(a){this._set("FirstName",a);this.updatePersonDetails()},_setLastNameAttr:function(a){this._set("LastName",a);this.updatePersonDetails()},_setLanguageCodeAttr:function(a){null!==a?this._set("LanguageCode",a):this._set("LanguageCode","");this.updateLanguageData()},_setBirthDateAttr:function(a){null!==a?this._set("BirthDate",a):this._set("BirthDate","");this.updatePersonDetails()},
updatePersonDetails:function(){this.personalDataItem.labelNode.innerHTML=this.FirstName+" "+this.LastName+", "+this.messages.BORN+" "+this.BirthDate},updateLanguageData:function(){if(dlg_language_select=e.byId("dlg_language_select")){var a="";null!==this.LanguageCode&&(a=dlg_language_select.map(this.LanguageCode));this.languageItem.labelNode.innerHTML=a}},postCreate:function(){var a=this;this.inherited(arguments);this.personalDetailsData.innerHTML=__t("Personal Details");this.languageData.innerHTML=
__t("Preferred Language");this.personalDataItem&&(this.personalDataItem.domNode._clickEvent&&c.disconnect(this.personalDataItem.domNode._clickEvent),this.personalDataItem.domNode._clickEvent=c.connect(this.personalDataItem.domNode,"click",function(b){b=e.byId("dlg_person_data");if(!b)return!1;b.set("FirstName",a.FirstName);b.set("LastName",a.LastName);b.set("BirthDate",a.BirthDate);b.show(function(b,d,c){a.set("FirstName",b);a.set("LastName",d);a.set("BirthDate",c);a.updateData()});return!0}));this.languageItem&&
(this.languageItem.domNode._clickEvent&&c.disconnect(this.languageItem.domNode._clickEvent),this.languageItem.domNode._clickEvent=c.connect(this.languageItem.domNode,"click",function(b){b=e.byId("dlg_language_select");if(!b)return!1;b.set("LanguageCode",a.LanguageCode);b.show(function(b){a.set("LanguageCode",b);a.updateData()});return!0}))},updateData:function(){var a=this;g.post(this.serviceUrl,{data:{"data[Person][per_first_name]":this.FirstName,"data[Person][per_last_name]":this.LastName,"data[Person][per_birth_date]":this.BirthDate,
"data[User][usr_lang_code]":this.LanguageCode},handleAs:"json"}).then(function(a){a.personid||Sys.message(a.error)},function(b){a.alert(a.errors.err101)})},refresh:function(){this.inherited(arguments);var a=this;this.query={id:"*",model:"user"};h(".header",this.domNode).forEach(function(b){a.headerNode=b});Sys.getUser()&&(this.dataUrl="function"===typeof this.serviceUrl?this.serviceUrl.call(this):this.substitute(this.serviceUrl,this),null!==this.dataUrl&&(this.processDataParams(),(this._store=new r({url:this.dataUrl,
hierarchical:!0}))&&null!==this._store&&this._store.fetch({query:this.query,queryOptions:{deep:!1},onComplete:function(b){for(var c in b){var d=b[c];a.set("FirstName",a._store.getValue(d,"first_name"));a.set("LastName",a._store.getValue(d,"last_name"));a.set("BirthDate",a._store.getValue(d,"birth_date"));a.set("LanguageCode",a._store.getValue(d,"language_code"))}},onError:function(b){a.alert(a.errors.err102)}})))}})});
//@ sourceMappingURL=SettingsView.js.map